### ISSUE TITLE
Single name variables make ipdb interaction problematic

### ISSUE THREAD

**Issue by alan-martinovic** [kipe/enocean#20]
Single name variables prevent autocomplete in ipdb.

(I use that step through approach to reverse engineer the objects methods.)

**Comment by kipe** [comment]
Can you explain this a bit further?
As I assume, you'll need to know the first letter of the variable when using auto-complete, so this shouldn't be an issue? :stuck_out_tongue: 

I personally don't like this change, mainly as I've become used to the single letter variables... Of course, if it really is an issue, this can be merged.

**Comment by romor** [comment]
Might be useful concerning this: Pylint - per default - complains about variable names with less than 3 characters, see: http://pylint-messages.wikidot.com/messages:c0103

In general, maybe integration of pylint checking would be useful? From my experience this is a helpful tool, much more than pep8. Do you think we could and should integrate it with travis-ci?

**Comment by kipe** [comment]
Yeah, the use of pylint would be a good choice.
Of course, I'll first need to see how much it complains ;)

**Comment by alan-martinovic** [comment]
My motivation for this issue was based on the way how I explore a new
library.
Usually I set a breakpoint at the beginning of example code after which I
step through it.

I used ipdb for this (since the time i started this issue I've discovered
that pydev allows visual debugging). In ipdb, during runtime, you can get
all the methods listed if you enter the variable name plus dot and than tab
for autocomplete whoch shows you all the methods and attributes of the
object.

This didn't work if variables had only single naming.

**Comment by kipe** [comment]
Thanks, I'll take this into consideration when looking over the pull request.

This and Pylint suggestion makes this a sure merge, I might make some of the variable names even longer though (for example using `packet` instead of `pack`). If we're using longer names, then there's really no point in using names which might be confused :wink:

**Comment by kipe** [comment]
Keeping this open for now, despite merge of #21, to remind of Pylint -checking.

**Comment by kipe** [comment]
Started working on Pylinting in [separate branch](https://github.com/kipe/enocean/tree/pylint). Soon to be merged though.

**Comment by kipe** [comment]
This is now merged, had to make some changes to the API, so beware!
