### ISSUE TITLE
Print the profile parameters as defined in the xml

### ISSUE THREAD

**Issue by alan-martinovic** [kipe/enocean#25]
When new people are exploring EnOcean and the library it would be very practical if the print of `p.parsed` would align to the order in the xml.
And the xml to follow the order specified in the protocol documentation :)

**Comment by kipe** [comment]
This should be easy enough fix, by changing the `Packet.parsed` to use [OrderedDict](https://docs.python.org/2/library/collections.html#collections.OrderedDict).
As for the XML following the protocol documentation ordering, that has always been my goal and should be done that way. If you find issues regarding this, PRs are always welcome :)

**Comment by kipe** [comment]
Oh, another thing I thought of but couldn't remember when writing the previous comment.
We could (and should) create a XML -> Markdown -generator, which would create `SUPPORTED_PROFILES.md`, allowing easier browsing of profiles through Github. In my opinion it should create something similar to the official documentation. Maybe leave out the bits, offsets etc, as they shouldn't be something the end-user ever touches (at least in the long run)...

**Comment by kipe** [comment]
Started work on this in [issue_25](https://github.com/kipe/enocean/compare/master...issue_25).
Come to think of it, this is actually quite a good request. It can be used enforce the order of the XML by removing `sorted` when checking the return values in tests. So adding label `unit tests required`, closing and merging the branch once all tests are updated.

**Comment by kipe** [comment]
Closed by 10cc345.
Separated `SUPPORTED_PROFILES.md` to separate issue #32.
