### ISSUE TITLE
Making the logging mechanism more customisable

### ISSUE THREAD

**Issue by alan-martinovic** [kipe/enocean#30]
I am just starting to work with the Python logging mechanism so additional comment are well appropriated. 
I believe the current logging implementation should be more customisable from the "library user" point of view.
Will do some experimenting but can't commit to a pull request any time soon.

Quote from [python logging documentation](https://docs.python.org/2.7/howto/logging.html#logging-basic-tutorial):

> It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

**Comment by kipe** [comment]
As said in the documentation, we shouldn't include any handlers. And as for the **library**, we don't.
The handler is currently only used in the examples, to give a fast start to new users reading the messages. Once again, it's the job of the end-user's application to implement the logging handlers way he/she needs it.
Thus, there shouldn't be any need to change the existing handler to be more customisable; `init_logging` shouldn't used by the end-user, if he doesn't want it.

**Comment by alan-martinovic** [comment]
> init_logging  shouldn't used by the end-user, if he doesn't want it

Didn't know this, sorry for the ignorance :)

**Comment by kipe** [comment]
Hehe, no worries :)
Using a generic logger for examples is quite a common practice, as it's the easiest and fastest way to start experimenting with libraries.
