### ISSUE TITLE
Re-structure Communicator

### ISSUE THREAD

**Issue by kipe** [kipe/enocean#34]
Based on discussion in 3bc29571ed1aef69f5b03bf1416e7bb15a072b1e

@romor wrote:

> Just my impression: I do not think that it is a nice solution to store a reference to communicator in `UTETeachIn` class. It could be provided as an argument to `send_response()` instead.
> 
> But even this is not nice, IMO. I do not think that a `Packet` class should autonomously send radio packets. I think this should be handled by the `Communicator` class instead.

@kipe wrote:

> Good points, and I agree with you.
> `Communicator` should indeed handle all sending and receiving, however I'm not sure if it's possible to implement without a reference at the moment. As the implementation is currently, the base `Communicator` doesn't implement any kind of loop. This makes it difficult to implement any kind of "packet interception" to the `Communicator` (I'd like all communicators to behave the same).
> 
> One option would be to call something like `Communicator.send_responses()` on each loop in the implementations. This would then check, if there's responses to be sent and sent them.
> 
> Another option would be to re-structure the communicators to implement a `SerialCommunicator.loop()` or something like that, which would take care of the implementation specific behavior, while `Communicator.run()` would implement the main loop. In this implementation, `SerialCommunicator.loop()` would return a list of new packages to be parsed, and `Communicator.run()` would take care of handling them (mainly putting to `receive` -queue), sending a response as needed.

**Comment by kipe** [comment]
For the second option;
The `Communicator` would then call `UTETeachIn.send_response(communicator=self, response=UTETeachIn.TEACHIN_ACCEPTED)`, if `Communicator.teach_in` is True.

**Comment by kipe** [comment]
Oh, by the way, I started using [waffle.io](https://waffle.io/kipe/enocean) to track the issues, so labels like `in progress` should be correct. Feel free to jump in on any issues in backlog :stuck_out_tongue_closed_eyes:

**Comment by romor** [comment]
> The Communicator would then call UTETeachIn.send_response(communicator=self, response=UTETeachIn.TEACHIN_ACCEPTED), if Communicator.teach_in is True.

Or even better: `Communicator` would call `UTETeachIn.create_response_packet()` and would put this packet in the send queue then.

**Comment by kipe** [comment]
Once again, good point :+1:

**Comment by kipe** [comment]
I also think we should change the queues to use [PriorityQueue](https://docs.python.org/2/library/queue.html#Queue.PriorityQueue), this way we could put the response packets to the top of the queue.
Requires some adjustments, but nothing too major compared to the current implementation...

**Comment by kipe** [comment]
@romor Is there reason to also change the `Communicator.receive` to `PriorityQueue`? Would it help in making custom responses, currently required for some 4BS -devices?

**Comment by kipe** [comment]
Hmm, now that I think of it, making receive queue a `PriorityQueue` would also help with catching responses from the device. Should help in situations like [this](https://github.com/kipe/enocean/blob/master/enocean/communicators/communicator.py#L87).

**Comment by kipe** [comment]
And now that I look at the code, it would require some fairly major changes to the API.
Currently the examples show fetching from the `receive` -queue directly with `communicator.receive.get()`, which would break if we set set tuples to the queue.

I'll now create `communicator.get_packet()`, and update the examples to match. After a while, we can change the `receive` queue to a prioritized version. I'll also start a changelog, to document especially the breaking API changes.

**Comment by romor** [comment]
I think there is no big demand for a `PriorityQueue` but it would be an improvement. I think we could priorize all packets of type `PACKET.RESPONSE`, which would include the address information but also the acknowledges for packets sent.

I think that using `communicator.get_packet()` is anyway the cleaner solution compared to accessing directly the queues from `Communicator`.
