### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Ethal** [kipe/enocean#35]
Hi,
When I used `sudo pip install enocean`,  I got the version 0.31 and not master branch ?
Thanks,

**Comment by kipe** [comment]
Of course wit [PyPI](https://pypi.python.org/pypi), you get the latest "stable"...
I haven't updated the version in PyPI in a while, as there's been so much going on.

I'm planning on releasing the next version to PyPI once the storage solution is merged.

**Comment by kipe** [comment]
Also, as mentioned in the readme (which should be updated), use `sudo pip install git+https://github.com/kipe/enocean.git` to get the "bleeding edge" -version.

**Comment by Ethal** [comment]
Noted
