### ISSUE TITLE
Issue with python 3.4+

### ISSUE THREAD

**Issue by Brueni92** [kipe/enocean#4]
When installing this package, I received an error and after a bit of googling I found the cause for the error here:
https://github.com/acrisci/i3ipc-python/issues/15

As far as I'm concerned, it is only an issue for python 3.4(+?).
So I suggest to replace enum34 with  enum-compat :)
Thanks for the app anyway

**Comment by kipe** [comment]
Thanks for the report, I'll look into it :)

**Comment by kipe** [comment]
Closed by 470874f3a46d073f4a91c99617037ef77b72042d, thanks for the issue report and suggestion fix. :smile:

**Comment by Brueni92** [comment]
your welcome, thanks for the fast fix 😊
