### ISSUE TITLE
Please create changelog and tag release versions

### ISSUE THREAD

**Issue by thom-nic** [kipe/enocean#42]
There are no releases tagged in Git or releases on Github for this package, yet there are several releases published on PyPi.  I tried using one of the examples under the `examples/` src directory with the latest release from PyPi but it appears there are significant changes in this repo since the last published release.  Without a changelog or tags it's very difficult to see what's changed between any of the published releases or even to correlate a git revision with any published release.

If you could please create tags for existing releases (or even the latest release!) then I can at least look at the examples folder as it existed for the latest published release in PyPi.  Thanks!

**Comment by kipe** [comment]
Sorry for my absence in the last few months, been way too busy with two jobs and finishing up my studies. I'll try and find the commit corresponding to the release and tag it. From now on, we'll provide tags for releases. Can't promise change logs, as it would most probably require too much time, but I'll at least try to include a link to the git log / history between the releases.

**Comment by thom-nic** [comment]
Thanks for the update!  Yeah I understand the release process takes time.  At the very least, tags for each release version makes it easy to browse commit logs.  Thanks again!

**Comment by kipe** [comment]
I now tagged the version 0.31, to what I hopefully identified correctly as the release 0.31 :smile: 
... It's quite a bit harder to try and look at these almost a year after the initial release, so at least that gives motivation to tag them appropriately from the get-go :stuck_out_tongue:
