### ISSUE TITLE
Occupancy Sensor and raw data package

### ISSUE THREAD

**Issue by nikitira** [kipe/enocean#47]
Sorry I'm new here. Didnt know how to pose a question or if this is ok. I have two issues:

first: I want to parse a data package for my PEHA enocean occupancy sensor. Am I right, that you are not supporting that yet?
snd: Is there a way to get the original data packet I receive from the serial port? Before you interprete and put it into a dict.

**Comment by kipe** [comment]
Hey,

To the first question: yes, it seems like the occupancy sensor uses profile `A5-07-01` which isn't in the `EEP.xml` yet.

To the second, I can't actually remember from the top of my head. The debug messages do however show all the information that goes to the packet parser, for example: 

`2017-02-06 19:58:05,549 - enocean.communicators.SerialCommunicator - DEBUG - 01:8E:56:0D->FF:FF:FF:FF (-74 dBm): 0x01 ['0xf6', '0xe0', '0x1', '0x8e', '0x56', '0xd', '0x20'] ['0x2', '0xff', '0xff', '0xff', '0xff', '0x4a', '0x0'] OrderedDict()`

The first array (`['0xf6', '0xe0', '0x1', '0x8e', '0x56', '0xd', '0x20']`) is the data of the message. The second array (`['0x2', '0xff', '0xff', '0xff', '0xff', '0x4a', '0x0']`) is the optional data, which includes stuff like destination etc.

Once you dive into the `EEP.xml`, it's fairly simple to add new profiles, just look at the official documentation and write the XML to match ;)

If there are any further questions, feel free to ask.
