### ISSUE TITLE
Get module ID

### ISSUE THREAD

**Issue by vdomos** [kipe/enocean#50]
Hello

I new on ocean devices.
I just tested a Nodon "Door / Windows sensor" (EPP: D5-00-01) with the example program: enocean_example.py.
This works well, I get the status of the switch:

    2017-05-10 14:56:10,467 - enocean.communicators.SerialCommunicator - DEBUG - 05:04:09:BD->FF:FF:FF:FF (-60 dBm): 0x01 ['0xd5', '0x8', '0x5', '0x4', '0x9', '0xbd', '0x0'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x3c', '0x0'] OrderedDict()
    CO: {u'value': u'open', u'description': u'Contact', u'unit': u'', u'raw_value': 0}

I will have a question for a dedicated use, how I can find the module ID in the code to make the difference between 2 identical devices ?
I see it in debug messages (05: 04: 09: BD) but I have not found a function allowing to use it.

Thank you for the work you have done and thank you for sharing it

**Comment by kipe** [comment]
It's stored in [RadioPacket.sender](https://github.com/kipe/enocean/blob/master/enocean/protocol/packet.py#L294-L300).
