### ISSUE TITLE
PTM215 DB sending teach-in requests

### ISSUE THREAD

**Issue by HarterHorst** [kipe/enocean#53]
Hi all,

i'm coming from [https://github.com/romor/enocean-mqtt](url) where I have an [issue](https://github.com/romor/enocean-mqtt/issues/1) with a PTM215 DB Switch. That repository is based on kipe/enocean and it receives the parsed RF messages.

Enocean-mqtt always tells me, that the incoming request is a learn request. The maintainer suggested to start a discussion here if such a switching actuator should raise teach-in requests at all.

Any ideas?

thanks

### Log of enocean_example.py

2017-06-28 09:34:38,870 - enocean.communicators.SerialCommunicator - DEBUG - FE:F9:59:1B->FF:FF:FF:FF (-48 dBm): 0x01 ['0xf6', '0x30', '0xfe', '0xf9', '0x59', '0x1b', '0x30'] ['0x3', '0xff', '0xff', '0xff', '0xff', '0x30', '0x0'] OrderedDict()
R1: {u'value': u'Button AO', u'description': u'Rocker 1st action', u'unit': u'', u'raw_value': 1}
EB: {u'value': u'pressed', u'description': u'Energy bow', u'unit': u'', u'raw_value': 1}
R2: {u'value': u'Button AI', u'description': u'Rocker 2nd action', u'unit': u'', u'raw_value': 0}
SA: {u'value': u'No 2nd action', u'description': u'2nd action', u'unit': u'', u'raw_value': 0}
T21: {u'value': True, u'description': u'T21', u'unit': u'', u'raw_value': 1}
NU: {u'value': True, u'description': u'NU', u'unit': u'', u'raw_value': 1}
2017-06-28 09:34:39,211 - enocean.communicators.SerialCommunicator - DEBUG - FE:F9:59:1B->FF:FF:FF:FF (-48 dBm): 0x01 ['0xf6', '0x0', '0xfe', '0xf9', '0x59', '0x1b', '0x20'] ['0x3', '0xff', '0xff', '0xff', '0xff', '0x30', '0x0'] OrderedDict()
R1: {u'value': u'Button AI', u'description': u'Rocker 1st action', u'unit': u'', u'raw_value': 0}
EB: {u'value': u'released', u'description': u'Energy bow', u'unit': u'', u'raw_value': 0}
R2: {u'value': u'Button AI', u'description': u'Rocker 2nd action', u'unit': u'', u'raw_value': 0}
SA: {u'value': u'No 2nd action', u'description': u'2nd action', u'unit': u'', u'raw_value': 0}
T21: {u'value': True, u'description': u'T21', u'unit': u'', u'raw_value': 1}
NU: {u'value': False, u'description': u'NU', u'unit': u'', u'raw_value': 0}

**Comment by DasBasti** [comment]
same issue here

**Comment by kipe** [comment]
Closed for the reasons described in https://github.com/kipe/enocean/pull/66#issuecomment-354481257

**Comment by ozett** [comment]
hi,
i followed the thread-starter up to here with the same problem.
i followed the "close"-links, but did not understand.

is this a bug - which is fixed in the lib? 
(how to get the fix, as i still have the same issue)

or is this an design-feature of the lib?
(and i also can not use the etako switch?)

maybe someone could clarify this?
thanks a lot
