### ISSUE TITLE
Serial I/O error can't be detected as serial port runs in a thread

### ISSUE THREAD

**Issue by J-A-M** [kipe/enocean#64]
When there is an error on the serial port, as the serial port is in a thread, the serial.SerialException is not propagated to the calling thread.  This means the serial thread continues to run, the port remain open a the calling thread is unaware of the issue.

Solution:
Change the code to exit the thread if there is an error, allowing the parent thread to restart it or raise the issue with the admin.

**Comment by kipe** [comment]
Closed via https://github.com/kipe/enocean/pull/65
