### ISSUE TITLE
Profile A5-07-01

### ISSUE THREAD

**Issue by sylvaincherrier** [kipe/enocean#68]
Hello,
i have a Mvt detector which used the A5-07-01 Profile.
I think the EEP.xml file should be update, because this profile seems to be given for temp sensor.
I have modified this file on my own computer in order to make my mvt detector been correctly recognized 
     <profile type="0x05" description="Occupancy">
        <data>
          <enum description="Occupancy" shortcut="PIR" offset="16" size="1">
            <item description="Off" value="0" />
            <item description="On" value="1" />
          </enum>
        </data>
      </profile>

I will make a pull request, if you agree on this update.

**Comment by kipe** [comment]
Closed via https://github.com/kipe/enocean/pull/69
