### ISSUE TITLE
EEP 2.6.3

### ISSUE THREAD

**Issue by Ethal** [kipe/enocean#7]
Hi,
here attached an update to EEP 2.6.3 , 

[EEP_2.6.3.xml.zip](https://github.com/kipe/enocean/files/77630/EEP_2.6.3.xml.zip)

Regards,

**Comment by kipe** [comment]
Could you please do this as a pull request, and also please note the message in commit 21cebd8dccb1659c314a033b7ed1ac8cae05ce44.

From now on, I'd like the EEP to follow the official documentation as closely as possible. Unfortunately this means unnecessary work for us, as EnOcean Alliance is reluctant to provide the official XML as open source :unamused:
