### ISSUE TITLE
Nodon - Profil VLD D2-01-12

### ISSUE THREAD

**Issue by kapwebdr** [kipe/enocean#70]
Hi,

i try to work this this product and this library 
http://nodon.fr/enocean/module-encastre-enocean-2-canaux-:-creez-un-va-et-vient-sans-fil_13-1

I think i have problem for send optionnal data to switch one of the two channel.

Any help with this ? 

Thank by advance, i use this in home-assistant.

**Comment by kipe** [comment]
Hmph...
Judging by the documentation, I would assume that it goes more or less the same as the example for `D1-01-01`: https://github.com/kipe/enocean/blob/master/examples/example_DO21-11B-E.py#L24

So the way it (might) work after adding the correct profile to `EEP.xml` (more or less a copy-paste from `D1-01-01`, preferably while adding the other commands and making a pull request :stuck_out_tongue_closed_eyes: )  is:
```python
# for turning on all channels
RadioPacket.create(rorg=RORG.VLD, rorg_func=0x01, rorg_type=0x12, destination=[0x01, 0x94, 0xB9, 0x46], sender=communicator.base_id, command=1, IO=0x1E, OV=0x64)
# for turning off all channels
RadioPacket.create(rorg=RORG.VLD, rorg_func=0x01, rorg_type=0x12, destination=[0x01, 0x94, 0xB9, 0x46], sender=communicator.base_id, command=1, IO=0x1E, OV=0x00)
# for turning on channel 1
RadioPacket.create(rorg=RORG.VLD, rorg_func=0x01, rorg_type=0x12, destination=[0x01, 0x94, 0xB9, 0x46], sender=communicator.base_id, command=1, IO=0x0x00, OV=0x64)
# for turning off channel 1
RadioPacket.create(rorg=RORG.VLD, rorg_func=0x01, rorg_type=0x12, destination=[0x01, 0x94, 0xB9, 0x46], sender=communicator.base_id, command=1, IO=0x0x00, OV=0x00)
```

**Comment by kapwebdr** [comment]
Yes ! 
Thank you, it's work ;) 
Really good job .

Have a good day & happy new year
