### ISSUE TITLE
Raw packet sending

### ISSUE THREAD

**Issue by argorain** [kipe/enocean#77]
Hello,

I like you package but I need to send raw packages without adding them to EEP.xml. Is there such way possible at this moment?

I somehow hacked this inside because I wasn't able to find anything such. Would you welcome and accept this enhancement as PR?

Thank you,
Vojtech

**Comment by Skeen** [comment]
This would be lovely, if for nothing else, just for debugging.

**Comment by argorain** [comment]
This seems to be solution. What I had in mind (and looked for and eventually written some draft for myself) is this: 

`packet = RadioPacket.create(rorg=RORG.BS4, RAWDATA=[0x30], RAWSTATUS=0x20)`

Basically keep access to it as is but add new kwargs which can be parsed and effectively override EEP access.
